config/routes.rb
Skyfall::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :trips

  root to: "home#index"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:foursquare]
  has_many :trips

  def self.find_for_foursquare_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.token = auth.credentials.token
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.foursquare_data"] && session["devise.foursquare_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]

  def after_sign_in_path_for(resource)
    trips_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @results = search_foursquare(@trip.location)
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = current_user.trips.build(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:location, :trip_start_date, :trip_end_date, :description)
    end

    def search_foursquare(location)
      client = Foursquare2::Client.new(
        :oauth_token => current_user.token, 
        :api_version => Time.now.strftime('%Y%m%d')
        )

      query = client.explore_venues(near: location, friendVisits: 'visited')

      query["groups"].first.items.map {|each|
        hash = {}
        hash["name"] = each["venue"]["name"]
        hash["lat"] = each["venue"]["location"]['lat']
        hash["long"] = each["venue"]["location"]['lng']
        hash["address"] = each["venue"]["location"]["address"]
        hash["url"] = each["venue"]["canonicalUrl"]
        hash
      }
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def foursquare
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_foursquare_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Foursquare") if is_navigational_format?
    else
      session["devise.foursquare_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Hopscotch</h1>
    <p>Find places where your friends have been in places you are going</p>
    <%= link_to "Sign in with Foursquare", user_omniauth_authorize_path(:foursquare), :class => 'btn btn-primary btn-lg' %>
</div>
</div>

<div class="product_info">
  <div class="container">
    <h1 class="title">Put your mark on the map</h1>
    <h2 class="subtitle">
      At Hopscotch, we want to help you get the most of your vacations. Instead of posting on Twitter or Foursquare and bugging your friends, we handle things the other way. Post where you want to go, and we go out and find things your friends recommend on Foursquare and Facebook (coming soon).
    </h2>

    <div class="row services">
      <div class="col-sm-4">
        <h2><i class="icon-picons-date-2"></i></h2>
        <h5>Plan your trip</h5>
        <p>
          Hopscotch works around your schedule. Enter in your trip start date and end date and we find amazing things for you to do.
        </p>
      </div>
      <div class="col-sm-4">
        <h2><i class="icon-picons-location"></i></h2>
        <h5>Going somewhere cool?</h5>
        <p>
          Enter in your location and all of the great places to visit are displayed on a beautiful responsive map. We highlight the top 10 places to go in each city.
        </p>
      </div>
      <div class="col-sm-4">
        <h2><i class="icon-picons-users-2"></i></h2>
        <h5>Powered by your friends</h5>
        <p>
          Sign in with Foursquare and find things to do that your friends can vouch for. No friends on Foursquare? We'll default to Foursquare's recommended places.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-custom">
  <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <div class="navbar-header">
              <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to 'Hopscotch', root_path, :class => 'navbar-brand' %>
          </div>
          <center>
              <div class="navbar-collapse collapse" id="navbar-main">
                  <ul class="nav navbar-nav">
                      <li>
                        <%= link_to 'Upcoming Trips', trips_path %>
                      </li>
                      <li>
                        <a href="#">Past Trips</a>
                      </li>
                      <li>
                        <a href="#">About Us</a>
                      </li>
                      <li>
                        <a href="#">Contact</a>
                      </li>
                  </ul>

                  <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
                        </ul>
                    <% end %>
                      </li>
                  </ul>
              </div>
          </center>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hopscotch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css' rel='stylesheet' />
  
  <!-- Fonts
  ================================================== -->
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if user_signed_in? %>
    <%= render 'layouts/header' %>
  <% end %>
  <% if notice %>
    <p class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= notice %>
    </p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= alert %>
    </p>
  <% end %>
  
  <div class='container-fluid'>
    <%= yield %>
  </div>

</body>
</html>

app/views/trips/_form.html.erb
<div class="panel-body">
  <%= form_for(@trip) do |f| %>
    <% if @trip.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

        <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :location %><br>
      <%= f.text_field :location, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :trip_start_date %><br>
      <%= f.date_select :trip_start_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :trip_end_date %><br>
      <%= f.date_select :trip_end_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create new trip", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<div class="header_buttons">
  <%= link_to 'Post new trip', new_trip_path, class: 'btn btn-primary' %>
</div>

<h1 class="title">Upcoming Trips</h1><br/>

  <div class="upcoming-trips clearfix">
    <% @trips.each do |trip| %>
    <div class="col-md-4">
      <ul>
        <li>
          <div class="post-image">
            <i class="icon-picons-earth"></i>
          </div>
          <h3><%= link_to trip.location, trip %></h3>
          <p>Notes: <%= trip.description %></p>
          <div class="meta">
            <span><i class="fa fa-calendar"></i><%= trip.trip_start_date %></span>
          </div>
        </li>
      </ul>
    </div>
    <% end %>
  </div>

<br>

app/views/trips/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New trip</h1>
  </div>

    <%= render 'form' %>
</div>

    <%= link_to 'Back', trips_path, class: "btn btn-primary" %>

app/views/trips/show.html.erb
<div class="header_buttons">
  <%= link_to 'Edit', edit_trip_path(@trip), class: "btn btn-warning" %>
  <%= link_to 'Back', trips_path, class: "btn btn-default" %>
</div>

<p>
  <h2 class="title"><%= @trip.location %></h2>
</p>

<div class="trip_info">
  <p>
    <h4>Leaving on:</h4>
    <h5><%= @trip.trip_start_date %></h5>

    <h4>Coming back:</h4>
    <h5><%= @trip.trip_end_date %></h5>

    <h4>Description:</h4>
    <h5><%= @trip.description %></h5>
  </p>
</div>

<div class="gmap">
  <div class="map-overlay-container">
    <div class="map-overlay" id="map-1042091">
      <ul class="map-menu">
        <% @results.take(8).each do |loc| %>
          <li><a href="#"><%= loc['name'] %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div id="googleMap" style="width:100%;height:380px;"></div>

  <script src="http://maps.googleapis.com/maps/api/js?sensor=false">
  </script>

  <script>
    function neighborhood_map(id) {
      $('#map-' + id).animate({width: 'toggle'}, '300');
    }

    function makeMarker(map, name, url, lat, long) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(lat,long),
        animation: google.maps.Animation.DROP, 
        map: map
      });

      var contentString = '<div id="content">'+
      '<div id="siteNotice">'+
      '</div>'+
      '<h1 id="firstHeading" class="firstHeading">' + name + '</h1>'+
      '<div id="bodyContent">'+
      '<p>' + url + '</p> '+
      '</div>'+
      '</div>';

      var infowindow = new google.maps.InfoWindow({
        content: contentString
      });

      google.maps.event.addListener(marker, 'click', function() {
        infowindow.open(map,marker);
      });
    }

    function initialize() {
      var mapProp = {
        center: new google.maps.LatLng(<%= @results.first['lat'] %>,<%= @results.first['long'] %>),
        zoom:11,
        mapTypeId:google.maps.MapTypeId.ROADMAP
        };
       map=new google.maps.Map(document.getElementById("googleMap")
        ,mapProp);

      <% @results.each do |loc| %>
        makeMarker(map, "<%= loc['name'] %>", "<%= loc['url'] %>", "<%= loc['lat'] %>", "<%= loc['long'] %>") 
      <% end %>
    }

    function drop() {
      for (var i =0; i < markerArray.length; i++) {
        setTimeout(function() {
          addMarkerMethod();
        }, i * 200);
      }
    }
    google.maps.event.addDomListener(window, 'load', initialize);
  </script>
</div>